[project]
name = "project-qwe"
version = "0.1.0"
description = "Something about python learnings"
readme = "README.md"
authors = [{ name = "Prasanna Kumar", email = "prasannaboga@gmail.com" }]
requires-python = ">=3.14,<3.15"
dependencies = [
    "alembic==1.19.1",
    "fastapi[standard]==0.141.1",
    "pydantic-settings>=2.15.0,<2.16.0",
    "python-dotenv>=1.2.2,<1.3.0",
    "sqlalchemy==2.0.51",
]

[dependency-groups]
dev = ["httpx>=0.28.1", "pytest>=8.3.4"]

[project.scripts]
project-qwe = "project_qwe:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
add-bounds = "minor"
