"""add status and due_at to todos

Revision ID: 9372e3b3c98f
Revises: 91db0bbf0fd7
Create Date: 2026-08-15 11:46:55.906113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9372e3b3c98f'
down_revision: Union[str, Sequence[str], None] = '91db0bbf0fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.Enum('created', 'process', 'completed', name='todostatus', native_enum=False, create_constraint=True), server_default='created', nullable=False))
    op.add_column('todos', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'due_at')
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
